name: Android OCR CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Compile debug with Gradle
        run: ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: openInWhatsapp-debug.apk
          path: app/build/outputs/apk/debug/*.apk
      - name: Compile release with Gradle
        run: ./gradlew assembleRelease
      - uses: actions/upload-artifact@v4
        with:
          name: openInWhatsapp-release.apk
          path: app/build/outputs/apk/release/*.apk
          
          